{% set name = "codechecker" %}
{% set version = "6.22.2.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cccc9b9f8e9bc5994590397893c2b42c1a53797b857d75956cf8a845e3c33ac

build:
  number: 0
  entry_points:
    - CodeChecker = codechecker_common.cli:main
    - merge-clang-extdef-mappings = codechecker_merge_clang_extdef_mappings.cli:main
    - post-process-stats = codechecker_statistics_collector.cli:main
    - report-converter = codechecker_report_converter.cli:main
    - tu_collector = tu_collector.tu_collector:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - alembic
    - gitpython
    - lxml
    - mypy_extensions
    - portalocker
    - psutil
    - python
    - pyyaml
    - sqlalchemy
    - thrift

test:
  commands:
    - CodeChecker --help
    - merge-clang-extdef-mappings --help
    - post-process-stats --help
    - report-converter --help
    - tu_collector --help

about:
  home: https://github.com/Ericsson/CodeChecker
  license: Apache-2.0 WITH LLVM-exception
  license_family: APACHE
  license_file: LICENSE.TXT
  summary: CodeChecker is an analyzer tooling, defect database and viewer extension
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - mwittgen
