{% set name = "codechecker" %}
{% set version = "6.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1f623bcce91e9a70d3e5af6dfff60b970c71b73160f85486844dbd3de17d849

build:
  number: 0
  entry_points:
    - CodeChecker = codechecker_common.cli:main
    - merge-clang-extdef-mappings = codechecker_merge_clang_extdef_mappings.cli:main
    - post-process-stats = codechecker_statistics_collector.cli:main
    - report-converter = codechecker_report_converter.cli:main
    - tu_collector = tu_collector.tu_collector:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - alembic
    - gitpython
    - lxml
    - mypy_extensions
    - portalocker
    - psutil
    - python
    - pyyaml
    - sqlalchemy
    - thrift

test:
  commands:
    - CodeChecker --help
    - merge-clang-extdef-mappings --help
    - post-process-stats --help
    - report-converter --help
    - tu_collector --help

about:
  home: https://github.com/Ericsson/CodeChecker
  license: Apache-2.0 WITH LLVM-exception
  license_family: APACHE
  license_file: LICENSE.TXT
  summary: CodeChecker is an analyzer tooling, defect database and viewer extension
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - mwittgen
